name: apply

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      environment_module:
        required: false
        type: string
        default: "general"

jobs:
  ${{ inputs.environment_module }}-apply:
    environment: ${{ inputs.environment }}-apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.environment }}-${{ inputs.environment_module }}

      - name: List everything
        run: |
          ls -la
