name: build

on:
  workflow_dispatch:

jobs:
  preview-plan:
    uses: ./.github/workflows/plan.yml

    with:
      environment: preview

  preview-apply:
    uses: ./.github/workflows/apply.yml
    needs: [preview-plan]

    with:
      environment: preview

  staging-plan:
    uses: ./.github/workflows/plan.yml

    with:
      environment: staging

  staging-apply:
    uses: ./.github/workflows/plan.yml
    needs: [preview-apply,staging-plan]

    with:
      environment: staging

  production-plan:
    uses: ./.github/workflows/plan.yml

    with:
      environment: production

  production-apply:
    uses: ./.github/workflows/apply.yml
    needs: [staging-apply,production-plan]

    with:
      environment: production
