name: cbc-build-production

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  pki-plan:
    uses: ./.github/workflows/plan.yml

    with:
      environment: ${{ inputs.environment }}
      environment_module: pki

  pki-apply:
    uses: ./.github/workflows/apply.yml
    needs: [pki-plan]

    with:
      environment: ${{ inputs.environment }}
      environment_module: pki

  ami-builder1-plan:
    uses: ./.github/workflows/plan.yml

    with:
      environment: ${{ inputs.environment }}
      environment_module: ami-builder1

  ami-builder1-apply:
    uses: ./.github/workflows/apply.yml
    needs: [ami-builder1-plan,pki-apply]

    with:
      environment: ${{ inputs.environment }}
      environment_module: ami-builder1

  ami-builder2-plan:
    uses: ./.github/workflows/plan.yml

    with:
      environment: ${{ inputs.environment }}
      environment_module: ami-builder2

  ami-builder2-apply:
    uses: ./.github/workflows/apply.yml
    needs: [ami-builder2-plan,ami-builder1-apply]

    with:
      environment: ${{ inputs.environment }}
      environment_module: ami-builder2

  ami-builder3-plan:
    uses: ./.github/workflows/plan.yml

    with:
      environment: ${{ inputs.environment }}
      environment_module: ami-builder3

  ami-builder3-apply:
    uses: ./.github/workflows/apply.yml
    needs: [ami-builder3-plan,ami-builder2-apply]

    with:
      environment: ${{ inputs.environment }}
      environment_module: ami-builder3

  ami-builder4-plan:
    uses: ./.github/workflows/plan.yml

    with:
      environment: ${{ inputs.environment }}
      environment_module: ami-builder4

  ami-builder4-apply:
    uses: ./.github/workflows/apply.yml
    needs: [ami-builder4-plan,ami-builder3-apply]

    with:
      environment: ${{ inputs.environment }}
      environment_module: ami-builder4

  ami-builder5-plan:
    uses: ./.github/workflows/plan.yml

    with:
      environment: ${{ inputs.environment }}
      environment_module: ami-builder5

  ami-builder5-apply:
    uses: ./.github/workflows/apply.yml
    needs: [ami-builder5-plan,ami-builder4-apply]

    with:
      environment: ${{ inputs.environment }}
      environment_module: ami-builder5

  ami-builder6-plan:
    uses: ./.github/workflows/plan.yml

    with:
      environment: ${{ inputs.environment }}
      environment_module: ami-builder6

  ami-builder6-apply:
    uses: ./.github/workflows/apply.yml
    needs: [ami-builder6-plan,ami-builder5-apply]

    with:
      environment: ${{ inputs.environment }}
      environment_module: ami-builder6

  ami-builder7-plan:
    uses: ./.github/workflows/plan.yml

    with:
      environment: ${{ inputs.environment }}
      environment_module: ami-builder7

  ami-builder7-apply:
    uses: ./.github/workflows/apply.yml
    needs: [ami-builder7-plan, ami-builder6-apply]

    with:
      environment: ${{ inputs.environment }}
      environment_module: ami-builder7
