name: cbc-build-preview

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  pki-plan:
    uses: ./.github/workflows/plan.yml

    with:
      environment: ${{ inputs.environment }}

  pki-apply:
    uses: ./.github/workflows/apply.yml
    needs: [pki-plan]

    with:
      environment: ${{ inputs.environment }}

  ami-builder1-plan:
    uses: ./.github/workflows/plan.yml

    with:
      environment: ${{ inputs.environment }}

  ami-builder1-apply:
    uses: ./.github/workflows/apply.yml
    needs: [ami-builder1-plan]

    with:
      environment: ${{ inputs.environment }}

  ami-builder2-plan:
    uses: ./.github/workflows/plan.yml

    with:
      environment: ${{ inputs.environment }}

  ami-builder2-apply:
    uses: ./.github/workflows/apply.yml
    needs: [ami-builder2-plan]

    with:
      environment: ${{ inputs.environment }}

  ami-builder3-plan:
    uses: ./.github/workflows/plan.yml

    with:
      environment: ${{ inputs.environment }}

  ami-builder3-apply:
    uses: ./.github/workflows/apply.yml
    needs: [ami-builder3-plan]

    with:
      environment: ${{ inputs.environment }}

  ami-builder4-plan:
    uses: ./.github/workflows/plan.yml

    with:
      environment: ${{ inputs.environment }}

  ami-builder4-apply:
    uses: ./.github/workflows/apply.yml
    needs: [ami-builder4-plan]

    with:
      environment: ${{ inputs.environment }}

  ami-builder5-plan:
    uses: ./.github/workflows/plan.yml

    with:
      environment: ${{ inputs.environment }}

  ami-builder5-apply:
    uses: ./.github/workflows/apply.yml
    needs: [ami-builder5-plan]

    with:
      environment: ${{ inputs.environment }}

  ami-builder6-plan:
    uses: ./.github/workflows/plan.yml

    with:
      environment: ${{ inputs.environment }}

  ami-builder6-apply:
    uses: ./.github/workflows/apply.yml
    needs: [ami-builder6-plan]

    with:
      environment: ${{ inputs.environment }}

  ami-builder7-plan:
    uses: ./.github/workflows/plan.yml

    with:
      environment: ${{ inputs.environment }}

  ami-builder7-apply:
    uses: ./.github/workflows/apply.yml
    needs: [ami-builder7-plan]

    with:
      environment: ${{ inputs.environment }}
