name: plan

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string


jobs:
  plan:
    environment: ${{ inputs.environment }}-plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: List everything
        run: |
          touch ${{ inputs.environment }}.tfplan

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.environment }}
          path: ${{ inputs.environment }}.tfplan
          retention-days: 5
